// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYSpwUAvesle9cA6jFvbZSCEHLbP46lI',
    appId: '1:330591949876:web:7dd48b8ca1bff38447a661',
    messagingSenderId: '330591949876',
    projectId: 'reot-logistic-warehouse',
    authDomain: 'reot-logistic-warehouse.firebaseapp.com',
    storageBucket: 'reot-logistic-warehouse.firebasestorage.app',
    measurementId: 'G-TNYFT25VXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7e5KEDnCxTzyCJX2_GHUCELGggDlXmwU',
    appId: '1:330591949876:android:0908e0a0368fca4f47a661',
    messagingSenderId: '330591949876',
    projectId: 'reot-logistic-warehouse',
    storageBucket: 'reot-logistic-warehouse.firebasestorage.app',
  );
}
